### ISSUE TITLE
Error when send a market SELL order from python.

### ISSUE THREAD

**Issue by AALVAREZG** [khramkov/MQL5-JSON-API#2]
When I send a market SELL ORDER from python (backtrader), JSON API translates it as BUY ORDER.
I traced the order and it seems that the following line of code in TradingModule produces a wrong conversion:
ENUM_ORDER_TYPE orderType=(ENUM_ORDER_TYPE) actionType; 

This is the trace code in this module, and result.
```
// Market orders
   if(actionType=="ORDER_TYPE_BUY" || actionType=="ORDER_TYPE_SELL"){
      Print("in tradingModule. Action type " + actionType);   
      ENUM_ORDER_TYPE orderType=(ENUM_ORDER_TYPE)actionType;
      Print("in tradingModule. Order type " + EnumToString(orderType));  

```
2019.08.13 20:38:57.742	JsonAPI (GDAXI,M1)	in tradingModule. Action 
type ORDER_TYPE_SELL
2019.08.13 20:38:57.742	JsonAPI (GDAXI,M1)	in tradingModule. Order 
type ORDER_TYPE_BUY

**Comment by khramkov** [comment]
Fixed. Please, get new version.
