### ISSUE TITLE
Pull request proposal; add push socket to push tick data

### ISSUE THREAD

**Issue by icve** [khramkov/MQL5-JSON-API#3]
Thank you for making this package, I am doing a university assignment where we have to connect a Python trade bot to MQL so that it can trade. I have not gotten the full requirements yet and I don't know anything about trade bots.

Do you think it would be useful if I add a new ZMQ push socket and push data obtained by calling `SymbolInfoTick`  in the `OnTick` function?

I can submit a pull request to implement that if that's useful;

edit: changed phrasing of question

**Comment by khramkov** [comment]
Yes. I think it would be useful. I can add data type param to "CONFIG" so the script will send candle/ticks via data socket.

Submit a pull request.
