### ISSUE TITLE
Socket time outs

### ISSUE THREAD

**Issue by junaidnasir** [khramkov/MQL5-JSON-API#5]
I am using the example class in readme and using 
```
rep = api.construct_and_send(action="ACCOUNT")
print(rep)
```
it works every 2nd time. I think it's some race condition such as socket replies before we start to listen, but I could be wrong.

**Comment by kafran** [comment]
@khramkov Hey Nikolai, is the architectural change to fix this too complex? Can you lead the way on fixing this?

**Comment by khramkov** [comment]
Hi all. Sorry fo long answer, i have really high load in the project.
Everything works fine. Some issues happens when when people try to use this code with threading.
Architectural changes will be made because REQ/REP scheme isn't stable.

**Comment by kafran** [comment]
@khramkov everything works here too. I read about the timeout on the instruction notes. Thank you very much for this project.
