### ISSUE TITLE
OnDeinit()

### ISSUE THREAD

**Issue by freedumb2000** [khramkov/MQL5-JSON-API#7]
I noticed OnDeinit() got removed in https://github.com/khramkov/MQL5-JSON-API/commit/9457e57890a740d51e756ae1ff83931a4c745bc8 .
Was there a specific reason for that? Is unbinding of the ports and removing the zmq context not needed?

Thanks :)

**Comment by khramkov** [comment]
No, it was a mistake. Fixed.

Thanks.
