### ISSUE TITLE
how to define position ID?

### ISSUE THREAD

**Issue by xkkubicek** [khramkov/MQL5-JSON-API#8]
Hi, first thank you for the perfect work. Could you please give me a hint how can I distinguish orders of one symbol? I want to close each trade at different time. If I use   POSITION_CLOSE_SYMBOL , it closes all opened positions of the symbol.  I tried to use POSITION_CLOSE_ID, but not successfully.  I have no idea how can I define ID for simple positions.  
Thanks

K. Kubicek

**Comment by khramkov** [comment]
Hi, thanks.
```python3
store = MTraderStore()
store.oapi.construct_and_send(action="TRADE", actionType="POSITION_CLOSE_ID", symbol="EURUSD", id=1034161189)
```

**Comment by xkkubicek** [comment]
it works...thanks
